spring:
  application:
    name: mscloudgateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
          lower-case-service-id: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://${KEYCLOAK_SERVE}:${KEYCLOAK_PORT}/realms/mscardauth

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://ez-eureka-server:senhansaber@${EUREKA_SERVE}:8761/eureka